imap_hibernate_timeout = 5 minutes

service imap-login {
  user = $SET:default_login_user
  inet_listener imap {
    listen = %{env:MDA_IMAP_LISTEN}
    port = %{env:MDA_IMAP_PORT}
  }
  inet_listener imaps {
    listen = %{env:MDA_IMAPS_LISTEN}
    port = %{env:MDA_IMAPS_PORT}
    ssl = %{env:MDA_IMAPS_TLS}
  }
  client_limit = 2000
  process_min_avail = 5
  process_limit = 20
}

service imap {
}

protocol imap {
  mail_plugins {
    imap_quota = yes
    imap_acl = yes
    imap_sieve = yes
    imap_filter_sieve = yes
  }
}
