service lmtp {
  inet_listener lmtps {
    listen = %{env:MDA_LMTP_LISTEN}
    port = %{env:MDA_LMTP_PORT}
    ssl = %{env:MDA_LMTP_TLS}
  }

}

protocol lmtp {
  mail_plugins {
    quota = yes
    sieve = yes
  }
}
