sieve_user_log_path = ~/.dovecot.sieve.log
sieve_plugins {
  sieve_imapsieve = yes
}

sieve_script system_before {
  type = before
  precedence = 10
  driver = dict
  name = before
  bin_path = ~/.sieve-bin
  dict proxy {
    name = sieve_system
    socket_path = dict-async
  }
}

sieve_script domain_before {
  type = before
  precedence = 20
  driver = dict
  name = before
  bin_path = ~/.sieve-bin
  dict proxy {
    name = sieve_domain
    socket_path = dict-async
  }
}

sieve_script user_before {
  type = before
  precedence = 30
  driver = dict
  name = before
  bin_path = ~/.sieve-bin
  dict proxy {
    name = sieve
    socket_path = dict-async
  }
}

sieve_script personal {
  type = personal
  driver = dict
  name = personal
  bin_path = ~/.sieve-bin
  dict proxy {
    name = sieve
    socket_path = dict-async
  }
}

sieve_script default {
  type = default
  driver = dict
  name = default
  bin_path = ~/.sieve-bin
  dict proxy {
    name = sieve
    socket_path = dict-async
  }
}

sieve_script system_global {
  type = global
  precedence = 10
  driver = dict
  name = global
  bin_path = ~/.sieve-bin
  dict proxy {
    name = sieve_system
    socket_path = dict-async
  }
}

sieve_script domain_global {
  type = global
  precedence = 20
  driver = dict
  name = global
  bin_path = ~/.sieve-bin
  dict proxy {
    name = sieve_domain
    socket_path = dict-async
  }
}

sieve_script user_global {
  type = global
  precedence = 30
  driver = dict
  name = global
  bin_path = ~/.sieve-bin
  dict proxy {
    name = sieve
    socket_path = dict-async
  }
}

sieve_script user_after {
  type = after
  precedence = 30
  driver = dict
  name = after
  bin_path = ~/.sieve-bin
  dict proxy {
    name = sieve
    socket_path = dict-async
  }
}

sieve_script domain_after {
  type = after
  precedence = 20
  driver = dict
  name = after
  bin_path = ~/.sieve-bin
  dict proxy {
    name = sieve_domain
    socket_path = dict-async
  }
}

sieve_script system_after {
  type = after
  precedence = 10
  driver = dict
  name = after
  bin_path = ~/.sieve-bin
  dict proxy {
    name = sieve_system
    socket_path = dict-async
  }
}

sieve_script discard {
  type = discard
  driver = dict
  name = discard
  bin_path = ~/.sieve-bin
  dict proxy {
    name = sieve
    socket_path = dict-async
  }
}
