#!/bin/sh
set -e
# Automatically added by dh_installsystemd/13.11.4+b4
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'dovecot.socket' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.11.4+b4
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'dovecot.service' >/dev/null || true
fi
# End automatically added section

#Remove links
if [ -h /bin/doveadm ]; then
    rm -f /bin/doveadm
fi
if [ -h /bin/doveconf ]; then
    rm -f /bin/doveconf
fi
if [ -h /bin/dovecot-sysreport ]; then
    rm -f /bin/dovecot-sysreport
fi
if [ -h /bin/sievec ]; then
    rm -f /bin/sievec
fi
if [ -h /bin/sieve-dump ]; then
    rm -f /bin/sieve-dump
fi
if [ -h /bin/sieve-filter ]; then
    rm -f /bin/sieve-filter
fi
if [ -h /bin/sieve-test ]; then
    rm -f /bin/sieve-test
fi